apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: {{ .Release.Namespace }}
data:
  realm.json: |
    {
      "realm": "fastboot",
      "enabled": true,
      "roles": {
        "realm": [
          { "name": "admin" },
          { "name": "developer" }
        ]
      },
      "clients": [
        {
          "clientId": "fastboot",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "fastboot",
          "directAccessGrantsEnabled": true
        }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "email": "admin@fastboot.io",
          "emailVerified": true,
          "firstName": "Admin",
          "lastName": "User",
          "requiredActions": [],
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["admin"]
        },
        {
          "username": "devuser",
          "enabled": true,
          "email": "devuser@fastboot.io",
          "emailVerified": true,
          "firstName": "Dev",
          "lastName": "User",
          "requiredActions": [],
          "credentials": [
            {
              "type": "password",
              "value": "123123",
              "temporary": false
            }
          ],
          "realmRoles": ["developer"]
        }
      ]
    }