apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.platform.auth.provider }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.platform.auth.provider }}
  ports:
    - port: {{ .Values.platform.auth.port }}
      targetPort: {{ .Values.platform.auth.port }}