global:
  domain: fastboot.local

platform:
  stage: local

artifactory:
  enabled: false

operator:
  image:
    repository: fastboot
    tag: local
    pullPolicy: Never
  service:
    type: LoadBalancer

  ingress:
    host: api.fastboot.local
    ingressClassName: traefik