name: Publish Helm Chart (OCI)

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # Extract version from Chart.yaml
      - name: Get chart version
        id: chart_version
        run: |
          VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Chart version is $VERSION"

      # Package chart
      - name: Package Helm chart
        run: |
          helm package ./

      # Login to GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | helm registry login ghcr.io -u suyogmankar --password-stdin

      # ✅ Push chart to OCI registry
      - name: Push Helm chart
        run: |
          helm push fastboot-helm-chart-${{ env.VERSION }}.tgz oci://ghcr.io/fastboot-io
